version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}