name: NestJs CI - main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clean install   
      run: yarn install --frozen-lockfile

    - name: Run linter
      run: yarn lint

    - name: Run unit tests
      run: yarn test

    - name: Build
      run: yarn build

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    
  build-python:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t python-microservice ./advanced-transformations-service/

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Login to Railway
      run: echo ${{ secrets.RAILWAY_TOKEN }} | railway login

    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}