name: NestJs CI - main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn build

    - name: Deploy to Railway
      uses: railwayapp/github-action@v1.2
      with:
        apiToken: ${{ secrets.RAILWAY_TOKEN }}
        environmentId: ${{ secrets.ENVIRONMENT_ID }}